Repository Software-Meister-High-School-Community/MOIZA-Spring-Boot-Server, pull requests merged in 2022-09, with the labels that each got.

#9 🔀 :: (#8) BaseEntity 설정
  moiza-infrasructure/build.gradle
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/entity/BaseTimeEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/entity/BaseUUIDEntity.java
Labels: 프로젝트 설정

#11 🔀 :: (#7) yml setting
  .github/CODEOWNERS
  moiza-infrasructure/src/main/resources/application.yml
Labels: 프로젝트 설정

#12 🔀 :: (#10) 패키지 구조 설정
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/annotation/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/error/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/response/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/exception/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/service/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notice/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notification/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/stups/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/viewcount/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/annotation/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/exception/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/mapper/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/dto/request/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/viewcount/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/config/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/error/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/fcm/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/.gitkeep
Labels: 프로젝트 설정

#16 🔀:: (#3) user entity 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/annotation/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/annotation/Aggregate.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/User.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/enums/DefaultImage.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/enums/School.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/enums/Sex.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/enums/UserType.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserMapper.java
Labels: 기능 추가

#15 🔀 :: (#13) ci setting
  .github/workflows/build.yml
  .github/workflows/ci.yml
  build.gradle
Labels: 프로젝트 설정

#14 🔀 :: (#4) Notification Entity 세팅
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notification/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notification/Notification.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notification/NotificationList.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notification/type/Type.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/User.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/NotificationEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/NotificationListEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/NotificationListId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/repository/NotificationListRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/repository/NotificationRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationListMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationListMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationMapper.java
Labels: 기능 추가

#22 🔀 :: (#20) Mapstruct 제거
  moiza-infrasructure/build.gradle
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/NotificationEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserMapperImpl.java
Labels: 리펙토링

#19 🔀 :: (#18) ci 버그
  .github/workflows/build.yml
  .github/workflows/ci.yml
  build.gradle
Labels: 버그

#23 🔀 :: (#21) UUID 리펙토링
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/domain/NotificationEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/entity/BaseTimeEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/entity/BaseUUIDEntity.java
Labels: Chore, 리펙토링, 버그

#24 🔀 :: (#4) Notice Entity 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notice/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notice/Notice.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/notice/NoticeAttachmentFile.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/domain/NoticeAttachmentFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/domain/NoticeEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/domain/repository/NoticeAttachmentFileRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/domain/repository/NoticeRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/mapper/NoticeAttachmentFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/mapper/NoticeAttachmentFileMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/mapper/NoticeMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notice/mapper/NoticeMapperImpl.java
Labels: 기능 추가

#25 🔀 :: (#11) UserDeviceToken entitiy 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/UserDeviceToken.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserDeviceTokenEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserDeviceTokenRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserDeviceTokenMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserDeviceTokenMapperImpl.java
Labels: 기능 추가

#17 🔀 :: (#5) 유저 소개 링크 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/error/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/error/ErrorProperty.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/error/MoizaException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/UserIntroduceLink.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/error/UserErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/exception/UserNotFoundException.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserIntroduceLinkEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserIntroduceLinkRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserIntroduceLinkMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserIntroduceMapperImpl.java
Labels: 프로젝트 설정

#27 🔀 :: (#12) UserSuspension entity 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/UserSuspension.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserSuspensionEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserSuspensionRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserSuspensionMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/UserSuspensionMapperImpl.java
Labels: 기능 추가

#28 🔀 :: comment관련 컴포넌트 엔티티
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/Comment.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/CommentAttatchmentFile.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/error/CommentErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/exception/CommentNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/error/FeedErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/exception/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/exception/FeedNotFoundException.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/MoizaSpringBootServerApplication.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/CommentAttatchmentFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/CommentEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/repository/CommentAttatchmentRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/repository/CommentRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/mapper/LocalFeedMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/mapper/PublicFeedMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/entity/BaseTimeEntity.java
Labels: 프로젝트 설정

#29 🔀 :: (#14) Report Entity 세팅
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/Report.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/comment/CommentReport.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/feed/FeedReport.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/UserReport.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/ReportEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/ReportRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/comment/CommentReportEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/comment/CommentReportId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/comment/repository/CommentReportRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/feed/FeedReportEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/feed/FeedReportId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/feed/repository/FeedReportRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/user/UserReportEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/user/UserReportId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/user/repository/UserReportRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/ReportMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/ReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/comment/CommentReportMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/comment/CommentReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/feed/FeedReportMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/feed/FeedReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/user/UserReportMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/user/UserReportMapperImpl.java
Labels: 프로젝트 설정

#30 🔀 :: (#13) SearchHistroy Entity 생성
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/SearchHistory.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/SearchHistoryEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/SearchHistoryRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/history/SearchHistoryMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/history/SearchHistoryMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userdevicetoken/UserDeviceTokenMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userdevicetoken/UserDeviceTokenMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userintroducelink/UserIntroduceLinkMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userintroducelink/UserIntroduceMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/usersuspension/UserSuspensionMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/usersuspension/UserSuspensionMapperImpl.java
Labels: 기능 추가

#31 🔀 :: (#25) Refresh Token Entity 세팅
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/RefreshToken.java
  moiza-infrasructure/build.gradle
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/RefreshTokenEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/repository/RefreshTokenRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/mapper/RefreshTokenMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/mapper/RefreshTokenMapperImpl.java
Labels: 프로젝트 설정

#32 🔀 :: (#16) Email Code Entity 세팅
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/EmailCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/type/Type.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/EmailCodeEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/repository/EmailCodeRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/mapper/EmailCodeMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/mapper/EmailCodeMapperImpl.java
Labels: 프로젝트 설정

#37 🔀 :: (#36) codecov setting
  .codecov.yml
  .github/workflows/ci.yml
  build.gradle
Labels: 프로젝트 설정

#39 🔀 :: (#37) 유저 아이디찾기
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/IdRecoveryApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/dto/response/IdRecoveryResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/usecase/IdRecoveryUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/usecase/IdValidationUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QueryUserSpi.java
  moiza-domain/src/test/java/auth/usecase/IdRecoveryUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/AuthWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/SecurityConfig.java
Labels: 기능 추가

#40 🔀 :: (#34) 유저 로그인
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/RefreshToken.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/UserSignInApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/dto/request/DomainUserSignInRequest.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/dto/response/SignInResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/UserInvalidPasswordException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/CommandRefreshTokenSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/CommandUserDeviceTokenSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/RefreshTokenSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/UserDeviceTokenSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/UserJwtSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/UserSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/dto/TokenResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/usecase/UserSignInUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/UserDeviceToken.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/error/UserErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QueryUserSpi.java
  moiza-domain/src/test/java/auth/usecase/UserSignInUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/RefreshTokenEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/mapper/RefreshTokenMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/AuthWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/dto/request/WebUserSignInRequest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userdevicetoken/UserDeviceTokenMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/RefreshTokenPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/UserDeviceTokenPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/JwtProvider.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/SecurityConfig.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/SecurityFacadeAdapter.java
Labels: 기능 추가

#42 🔀 :: (#39) 비밀번호 변경 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/UpdatePasswordApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/api/dto/request/DomainUpdatePasswordRequest.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/error/AuthErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/InvalidPasswordException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/AuthSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/usecase/IdValidationUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/usecase/UpdatePasswordUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/domain/User.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QueryUserSpi.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/AuthWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/dto/request/WebUpdatePasswordRequest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/PublicFeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/SecurityFacadeAdapter.java
Labels: 기능 추가

#43 🔀 :: (#52) Conflict 해결
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/domain/adapter/RefreshTokenPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/CommentAttatchmentFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/CommentEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/repository/CommentAttatchmentRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/repository/CommentRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/comment/CommentReportId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/comment/CommentReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserDeviceTokenPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/persistence/RefreshTokenPersistenceAdapter.java
Labels: 버그

#44 🔀 :: (#53) 소나클라우드 정리
  moiza-domain/src/test/java/auth/usecase/UserSignInUseCaseTest.java
  moiza-domain/src/test/java/user/usecase/UserSignUpUseCaseTest.java
  moiza-infrasructure/build.gradle
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/auth/presentation/AuthWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/util/EmailCodeRandomStringUtilAdapter.java
Labels: Chore, 리펙토링

#47 🔀 :: (#47) 전체 유저 검색 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/SearchAllUsersApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/response/SearchAllUsersResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QueryUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/SearchAllUserUseCase.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/custom/UserRepositoryCustom.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/custom/UserRepositoryCustomImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/vo/QuerySearchAllUsersVO.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가

#46 🔀 :: (#41) 사용자 회원탈퇴 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/error/AuthErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/UserAuthQueryFailedException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/UserDeleteApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/UserDeleteUseCase.java
  moiza-domain/src/test/java/user/usecase/UserDeleteUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/global/security/SecurityFacadeAdapter.java
Labels: 기능 추가

#49 🔀 :: (#46) 졸업생 인증 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/GraduateVerificationApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/request/DomainGraduateVerificationRequest.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/domain/GraduateVerifyingFile.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandGraduateVerifyingFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/GraduateVerifyingFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/GraduateVerificationUseCase.java
  moiza-domain/src/test/java/user/usecase/GraduateVerificationUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/GraduateVerifyingFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/GraduateVerifyingFileAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/GraduateVerifyingFileRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/graduateverifyingfile/GraduateVerifyingFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/graduateverifyingfile/GraduateVerifyingFileMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/dto/request/WebGraduateVerificationRequest.java
Labels: 기능 추가

#50 🔀 :: (#40) 유저 프로필 보기
  .github/workflows/ci.yml
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/QueryUserProfileDetailApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/response/IntroduceLinkUrlResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/response/UserProfileDetailsResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/UserIntroduceLinkSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/UserQueryIntroduceLinkSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/QueryUserProfileDetailUseCase.java
  moiza-domain/src/test/java/user/usecase/UserIntroduceLinkUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserIntroduceLinkPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserIntroduceLinkRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가
