Repository Software-Meister-High-School-Community/MOIZA-Spring-Boot-Server, pull requests merged in 2022-10, with the labels that each got.

#48 🔀 :: (#50) 유저 검색 기록 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/UserSearchHistoryApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/response/UserSearchHistoryResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/error/SearchHistoryErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/exception/SearchHistoryNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QuerySearchHistorySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/SearchHistorySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/UserSearchHistoryUseCase.java
  moiza-domain/src/test/java/user/usecase/UserSearchHistoryUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/SearchHistoryPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/SearchHistoryRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가

#51 🔀 :: (#48) 사용자 정보수정
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/UserEditApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/request/DomainUserEditRequest.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandUserIntroduceLinkSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/CommandUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/UserIntroduceLinkSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/UserEditUseCase.java
  moiza-domain/src/test/java/auth/usecase/UserEditUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/UserEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserIntroduceLinkPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/UserPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserIntroduceLinkRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userintroducelink/UserIntroduceLinkMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/mapper/userintroducelink/UserIntroduceMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/dto/request/WebUserEditRequest.java
Labels: 기능 추가

#52 🔀 :: (#51) 검색기록 삭제 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/UserSearchHistoryDeleteApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/error/SearchHistoryErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/exception/HistoryPermissionDeniedException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/QuerySearchHistorySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/UserSearchHistoryDeleteUseCase.java
  moiza-domain/src/test/java/user/usecase/UserSearchHistoryDeleteUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/adapter/SearchHistoryPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가

#54 🔀 :: (#42) 마이페이지 api
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/FeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/QueryFeedSqi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/FollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/QueryFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/QueryUserMyPageApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/api/dto/response/MyPageResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/usecase/QueryUserMyPageUseCase.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/FeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/FeedRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/adapter/FollowPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/repository/FollowRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가

#55 🔀 :: (#49) 유저 신고하기
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/spi/CommandReportSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/api/UserReportApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/domain/UserReport.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/error/UserReportErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/exception/UserReportNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/spi/CommandUserReportSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/spi/QueryUserReportSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/spi/UserReportSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/report/user/usecase/UserReportUseCase.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/adapter/ReportAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/user/adapter/QueryUserReportPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/domain/user/adapter/UserReportAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/user/UserReportMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/user/UserReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/presentatoin/ReportWebAdapter.java
Labels: 기능 추가

#53 🔀 :: (#44) 팔로우하기 api 등등
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/AuthSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/api/CancelFollowApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/api/DeleteFollowApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/api/FollowUserApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/error/FollowErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/exception/FollowNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/CommandFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/FollowAuthSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/FollowQueryUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/FollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/QueryFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/CancelFollowUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/DeleteFollowUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/FollowUserUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/UserSpi.java
  moiza-domain/src/test/java/follow/CancelFollowUseCaseTest.java
  moiza-domain/src/test/java/follow/DeleteFollowUseCaseTest.java
  moiza-domain/src/test/java/follow/FollowUserUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/FollowEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/adapter/FollowPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/repository/FollowRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/mapper/FollowMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/presentation/FollowWebAdapter.java
Labels: 기능 추가

#62 🔀 :: (#61) 게시글 좋아요 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/api/AddFeedLikeApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/error/FeedLikeErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/exception/FeedLikeAlreadyExistsException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/CommandFeedLikeSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/FeedLikeQuerySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/FeedLikeSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/usecase/AddFeedLikeUseCase.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/WebFeedAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/adapter/FeedLikePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/repository/FeedLikeRepository.java
Labels: 기능 추가

#61 🔀 :: (#65) 게시글 삭제 버그
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/spi/CommandCommentAttachmentFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/spi/CommandCommentSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/feed/CommandFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/feedattachmentfile/CommandFeedAttachmentFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/feedcategory/CommandFeedCategorySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/localfeed/CommandLocalFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/CommandPublicFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/usecase/DeleteFeedUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/CommandFeedLikeSpi.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/adapter/CommentAttachmentFilePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/adapter/CommentPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/repository/CommentAttachmentFileRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/repository/CommentRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feed/FeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feedattaachmentfile/FeedAttachmentFilePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feedcategory/FeedCategoryPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/localfeed/LocalFeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/publicfeed/PublicFeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/FeedCategoryRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/adapter/FeedLikePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/repository/FeedLikeRepository.java
Labels: 리펙토링

#63 🔀 :: (#57) 좋아요 취소 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/usecase/DeleteFeedUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/api/DiscardFeedLikeApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/error/FeedLikeErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/exception/FeedLikeNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/CommandFeedLikeSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/spi/FeedLikeQuerySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/like/usecase/DiscardFeedLikeUseCase.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/WebFeedAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/adapter/FeedLikePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/domain/repository/FeedLikeRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/custom/UserRepositoryCustomImpl.java
Labels: 기능 추가

#58 🔀 :: (#58) 게시글 조회 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/PublishedFeedListApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/dto/response/PublishedFeedListResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/dto/response/PublishedFeedResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/response/.gitkeep
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/dto/response/PublishedFeedPage.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/dto/response/PublishedFeedResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/PublicFeedQuerySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/PublicFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/type/QueryOrders.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/usecase/PublishedFeedListUseCase.java
  moiza-domain/src/test/java/feed/usecase/PublishedFeedListUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedCategoryEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedCategoryId.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/PublicFeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feedcategory/FeedCategoryPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/publicfeed/PublicFeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/custom/PublicFeedRepositoryCustom.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/custom/PublicFeedRepositoryCustomImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/FeedWebAdapter.java
Labels: 기능 추가

#60 🔀 :: (#59) 임시게시글 조회 API
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/LocalFeedListApi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/response/LocalFeedListResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/api/response/LocalFeedResponse.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/error/FeedErrorCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/localfeed/LocalFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/localfeed/QueryLocalFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/usecase/LocalFeedListUseCase.java
  moiza-domain/src/test/java/feed/usecase/LocalFeedListUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/localfeed/LocalFeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/custom/LocalFeedCustomRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/custom/LocalFeedCustomRepositoryImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/exception/BadFeedTypeException.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/FeedPresentationConfiguration.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/WebFeedAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/dto/converter/FeedTypeConverter.java
Labels: 기능 추가

#64 🔀 :: (#67) 휴먼에러 정정
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/domain/EmailCode.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/AuthCodeAlreadyVerifiedException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/EmailCodeNotVerifiedException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/EmailCodeNotfoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/InvalidPasswordException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/exception/RefreshTokenNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/auth/spi/AuthSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/CommentAttachmentFile.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/exception/CommentNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/spi/CommandCommentAttachmentFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/spi/CommandCommentSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/comment/spi/CommentAttachmentFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/enums/FeedType.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/exception/FeedNotFoundException.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/feed/CommandFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/feedattachmentfile/CommandFeedAttachmentFileSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/CommandPublicFeedSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/spi/publicfeed/type/QueryOrders.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/feed/usecase/DeleteFeedUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/CommandFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/FollowAuthSecuritySpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/FollowQueryUserSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/FollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/spi/QueryFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/FollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/sqi/QueryFollowSpi.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/CancelFollowUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/DeleteFollowUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/follow/usecase/FollowUserUseCase.java
  moiza-domain/src/main/java/com/moiza/moizaspringbootserver/user/spi/UserSpi.java
  moiza-domain/src/test/java/follow/CancelFollowUseCaseTest.java
  moiza-domain/src/test/java/follow/DeleteFollowUseCaseTest.java
  moiza-domain/src/test/java/follow/FollowUserUseCaseTest.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/CommentAttachmentFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/adapter/CommentAttachmentFilePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/adapter/CommentPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/domain/repository/CommentAttachmentFileRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttachmentFileImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttachmentFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/comment/mapper/CommentAttatchmentFileMapper.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedAttachmentFileEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/PublicFeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feed/FeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feedattaachmentfile/FeedAttachmentFilePersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/publicfeed/PublicFeedPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/exception/.gitkeep
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/FollowEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/adapter/FollowPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/domain/repository/FollowRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/follow/mapper/FollowMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/like/mapper/FeedLikeMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/notification/mapper/NotificationListMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/ReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/comment/CommentReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/feed/FeedReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/report/mapper/user/UserReportMapperImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/user/domain/repository/UserIntroduceLinkRepository.java
Labels: 리펙토링

#65 🔀 :: (#68) 게시글 에러 수정
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedCategoryEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/FeedEntity.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/adapter/feedcategory/FeedCategoryPersistenceAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/FeedCategoryRepository.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/domain/repository/custom/PublicFeedRepositoryCustomImpl.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/FeedWebAdapter.java
  moiza-infrasructure/src/main/java/com/moiza/moizaspringbootserver/domain/feed/presentation/WebFeedAdapter.java
Labels: 버그

#57 🔀 :: (#55) CodeCov setting failed
  .github/workflows/ci.yml
  build.gradle
  moiza-infrasructure/src/main/resources/application.yml
Labels: 버그
